
project_id = "qrdulwzjgbfgaplazgsh"

[functions.gemini-ai]
verify_jwt = false

[functions.ai-content-processor]
verify_jwt = false

[functions.advanced-analytics]
verify_jwt = false

[functions.data-validator]
verify_jwt = false

[functions.file-processor]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false

[functions.security-monitor]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.ionos-api]
verify_jwt = false

[functions.deployment-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
