name: Deploy Notes App to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/notes-app/**'
      - '.github/workflows/deploy-notes-app.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./apps/notes-app
        run: pnpm install --frozen-lockfile

      - name: Build app
        working-directory: ./apps/notes-app
        env:
          NODE_ENV: production
        run: |
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./apps/notes-app/dist
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
