name: Deploy All ONAI Applications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm install
      
    - name: Install all app dependencies
      run: npm run install:all
      
    - name: Build all applications
      run: npm run build:all
      
    - name: Deploy Notes App
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/notes-app/dist
        destination_dir: notes-app
        
    - name: Deploy Marketing Website
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/marketing-website/dist
        destination_dir: marketing-website
        
    - name: Deploy Payment System
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/payment-system/dist
        destination_dir: payment-system

